In [36]:
import torch
import numpy as np

In [34]:
from __future__ import print_function
x = torch.Tensor(5, 3)
x = torch.rand(5, 3)
x

tensor([[ 0.5384,  0.7395,  0.5164],
        [ 0.8924,  0.4571,  0.0603],
        [ 0.0554,  0.8588,  0.4809],
        [ 0.1766,  0.8969,  0.7824],
        [ 0.1570,  0.1466,  0.8669]])

In [19]:
x.size()

torch.Size([5, 3])

In [7]:
y = torch.rand(5, 3)

In [8]:
x + y

tensor([[ 0.6584,  0.6771,  1.0815],
        [ 1.0294,  1.0246,  0.9433],
        [ 0.6888,  0.2434,  0.3968],
        [ 0.8548,  1.1329,  1.3702],
        [ 0.3823,  0.1760,  0.4995]])

In [9]:
torch.add(x, y)

tensor([[ 0.6584,  0.6771,  1.0815],
        [ 1.0294,  1.0246,  0.9433],
        [ 0.6888,  0.2434,  0.3968],
        [ 0.8548,  1.1329,  1.3702],
        [ 0.3823,  0.1760,  0.4995]])

In [17]:
result = torch.Tensor(5, 3)

In [20]:
torch.add(x, y, out = result)

tensor([[ 1.1823,  1.1414,  2.0695],
        [ 1.2966,  1.6742,  1.3193],
        [ 1.1536,  0.4089,  0.6012],
        [ 1.3786,  1.7584,  2.0945],
        [ 0.3983,  0.2861,  0.6466]])

In [21]:
result

tensor([[ 1.1823,  1.1414,  2.0695],
        [ 1.2966,  1.6742,  1.3193],
        [ 1.1536,  0.4089,  0.6012],
        [ 1.3786,  1.7584,  2.0945],
        [ 0.3983,  0.2861,  0.6466]])

In [22]:
y.add_(x)

tensor([[ 1.1823,  1.1414,  2.0695],
        [ 1.2966,  1.6742,  1.3193],
        [ 1.1536,  0.4089,  0.6012],
        [ 1.3786,  1.7584,  2.0945],
        [ 0.3983,  0.2861,  0.6466]])

In [23]:
y

tensor([[ 1.1823,  1.1414,  2.0695],
        [ 1.2966,  1.6742,  1.3193],
        [ 1.1536,  0.4089,  0.6012],
        [ 1.3786,  1.7584,  2.0945],
        [ 0.3983,  0.2861,  0.6466]])

In [24]:
y.add(x)

tensor([[ 1.7062,  1.6058,  3.0576],
        [ 1.5638,  2.3237,  1.6954],
        [ 1.6185,  0.5744,  0.8055],
        [ 1.9025,  2.3839,  2.8188],
        [ 0.4143,  0.3962,  0.7936]])

In [27]:
x[:, 1]

tensor([ 0.4644,  0.6496,  0.1655,  0.6255,  0.1101])

In [28]:
x

tensor([[ 0.5239,  0.4644,  0.9881],
        [ 0.2672,  0.6496,  0.3761],
        [ 0.4649,  0.1655,  0.2043],
        [ 0.5239,  0.6255,  0.7243],
        [ 0.0160,  0.1101,  0.1471]])

In [29]:
a = torch.ones(5)

In [30]:
b = a.numpy()

In [32]:
a.add_(1)
print(a)
print(b)

tensor([ 3.,  3.,  3.,  3.,  3.])
[ 3.  3.  3.  3.  3.]


In [37]:
a = np.ones(5)

In [38]:
b = torch.from_numpy(a)

In [39]:
np.add(a, 1, out = a)

array([ 2.,  2.,  2.,  2.,  2.])

In [40]:
print(a)

[ 2.  2.  2.  2.  2.]


In [41]:
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


In [42]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

In [43]:
print(torch.cuda.is_available())

False


In [51]:
from torch.autograd import Variable

In [54]:
x = torch.randn(3)
x = Variable(x, requires_grad = True)
y = x + 2

In [56]:
x

tensor([-0.3751, -0.5757,  0.9309])

In [52]:
x = torch.randn(3)
x = Variable(x, requires_grad = True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)
x.grad

tensor([  102.4000,  1024.0000,     0.1024])

In [57]:
y

tensor([ 1.6249,  1.4243,  2.9309])

In [60]:
x = torch.randn(3)
x = Variable(x, requires_grad = True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)
x.grad

tensor([  102.4000,  1024.0000,     0.1024])

In [62]:
torch.rand(1, 10)

tensor([[ 0.7588,  0.9077,  0.8351,  0.4403,  0.9311,  0.4192,  0.2281,
          0.7509,  0.0144,  0.6369]])

In [65]:
from __future__ import print_function

import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    """docstring for Net"""
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 5) # 1 input image channel, 6 output channels, 5x5 square convolution kernel
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)# an affine operation: y = Wx + b
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2)) # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv2(x)), 2) # If the size is a square you can only specify a single number
        x = x.view(-1, self.num_flat_features(x)) # feature_map to features
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]# all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

net = Net()
print(net)

params = list(net.parameters())
print(len(params))
print(params[0].size())

# 定义输入数据
input = Variable(torch.randn(1, 1, 32, 32))
# 前向传播
out = net(input)

print(out)

# net.zero_grad() # 对所有的参数的梯度缓冲区进行归零
# out.backward(torch.randn(1, 10)) # 使用随机的梯度进行反向传播

target = Variable(torch.rand(1, 10))
criterion = nn.MSELoss()
loss = criterion(out, target)

print(loss)

# For illustration, let us follow a few steps backward
# print(loss.creator) # MSELoss
# print(loss.creator.previous_functions[0][0]) # Linear
# print(loss.creator.previous_functions[0][0].previous_functions[0][0]) # ReLU

net.zero_grad()
print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)
loss.backward()
print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)
10
torch.Size([6, 1, 5, 5])
tensor([[ 0.0472, -0.0343,  0.0963,  0.0448, -0.0286, -0.1476, -0.0130,
         -0.1109, -0.0423,  0.0712]])
tensor(0.2951)
conv1.bias.grad before backward
None
conv1.bias.grad after backward
tensor(1.00000e-03 *
       [ 3.3507, -6.3969,  0.2685, -3.8588,  5.3214,  2.7469])
